const commands = {
    test: "test recieved :D",
    whoami: "you are you, obviously",
    version: "v1.0.0.0 Initial Release! If you are seeing this from HackClub, shoot me a dm on slack for a suprise!",
    selfDestruct: "Run. Self destructing in 3...",
    gaslight: "Error 404, gaslight not a real command",
    status: "If you are reading this, terminal working ig?",
    ping: "Pong",
    hi: "Hi there! You liking GenericOS?",
    hello: "Hi there! You liking GenericOS?",
    bye: "Don't leave me pwease 👉️👈️",
    goodbye: "Dont leave me pwease 👉️👈️",
    sudo: "Nice try. You have no power here.",
    rm: "Deleting system32...",
    ls: "Documents  Pictures  readme.txt  ... go check File Explorer stop being lazy.",
    cd: "There's no 'cd'-ing here, what do you think this is, windows?",
    clear: "how about no",
    date: () => new Date().toString(),
    time: () => new Date().toLocaleTimeString(),
    echo: "echoooo echooooooo echooooooooooooooooo",
    exit: "There is no escape. Just close the window like a normal person.",
    coffee: "Error 418: I'm a teapot, not a coffee maker.",
    love: "Aww, I love you too <3",
    hate: "That's not very nice :(",
    joke: "Knock knock",
    credits: "Made entirely from scratch by Jack Jacobson. No template, no guide, all custom.",
    about: "Try opening the About app on the desktop stop being lazy",
    apps: "Notepad, Terminal, Minesweeper, Web Browser, About, File Explorer. More coming soon.",
    banner: "  ____                      _      ____   _____ \n / ___| ___ _ __   ___ _ __(_) ___/ ___| |_   _|\n| |  _ / _ \\ '_ \\ / _ \\ '__| |/ __\\___ \\   | |  \n| |_| |  __/ | | |  __/ |  | | (___ ___) |  | |  \n \\____|\\___|_| |_|\\___|_|  |_|\\___|____/   |_|  ",
    uptime: "This session has been running for exactly as long as you've had this tab open.",
    reboot: "Try the power menu in the taskbar for that.",
    shutdown: "Try the power menu in the taskbar for that.",
    coinflip: () => (Math.random() < 0.5 ? "Heads" : "Tails"),
    diceroll: () => "You rolled a " + (Math.floor(Math.random() * 6) + 1),
    year: () => "It is currently " + new Date().getFullYear(),
    help: "The following are usable commands, youll have to use them yourself to figure out what they do. COMMANDS ARE CASE SENSITIVE\n\ntest\nwhoami\nversion\nselfDestruct\ngaslight\nstatus\nping\nhi\nhello\nbye\ngoodbye\nsudo\nrm\nls\ncd\nclear\ndate\ntime\necho\nexit\nmatrix\ncoffee\nlove\nhate\njoke\nsecret\ncredits\nabout\napps\nbanner\nuptime\nreboot\nshutdown\ncoinflip\ndiceroll\nyear"
};